name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Run go test (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [central, chunk-server]
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
